version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal_website
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - .pnpm-store:/app/.pnpm-store
    environment:
      - .env.local
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
